### ISSUE TITLE
Trouble while apply `com.redmadrobot.detekt` with `FAIL_ON_PROJECT_REPOS` repositories mode

### ISSUE THREAD

**Issue by rwqwr** [RedMadRobot/gradle-infrastructure#104]
While using gradle [Centralizing repositories declaration](https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration) with repositories mode `FAIL_ON_PROJECT_REPOS` project sync fails with exception

```text
Build was configured to prefer settings repositories over project repositories but repository 'MavenRepo' was added by plugin 'com.redmadrobot.detekt'
```

The workaround in this case is to use the `PREFER_SETTINGS` repositories mode and the project will successfully synced and built, but a warning will appear in the console.

```text
Build was configured to prefer settings repositories over project repositories but repository 'MavenRepo' was added by plugin 'com.redmadrobot.android-library'
Build was configured to prefer settings repositories over project repositories but repository 'Google' was added by plugin 'com.redmadrobot.android-library'
Build was configured to prefer settings repositories over project repositories but repository 'MavenRepo2' was added by plugin 'com.redmadrobot.detekt'
```

Can a plugin use the repositories defined in the project?

**Comment by osipxd** [comment]
In the next version you will be able to disable repositories adding using option `redmadrobot.add.repositories = false`

**Comment by rwqwr** [comment]
The problem still exists with the `com.redmadrobot.detekt` plugin. :)

Also, I think it would be useful to add a note about the new property in the `README` file under **`Troubleshooting`**.
