### ISSUE TITLE
Make gradle-infrastructure compatible with Kotlin 1.6 (Gradle 7.5.1)

### ISSUE THREAD

**Issue by EnterYourMail** [RedMadRobot/gradle-infrastructure#127]
When I have the kotlin-dsl plugin (plugin section) and the gradle-infrastructure (0.18) plugin (dependency section) at a BuildSrc gradle file, I get the error:

> Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.8.10, expected version is 1.6.21

- implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.8.10")) - at app gradle file.
- Gradle 7.5.1, AGP 7.3.1 (7.4.2).

As far as I know Gradle 7.5.1 (kotlin-dsl) has the embedded version of 1.6.21

I did many experiments, and when I set `kotlin-dsl` apply false, I got the error of incompatible Java 8 and Java 11.

**Comment by osipxd** [comment]
Reproduced.
It looks like the issue appears only if all of these conditions:
- we have `buildSrc`
- any of the gradle-infrastructure plugins added to `dependencies` in `buildSrc` module
- plugin `kotlin-dsl` should be applied to `buildSrc` module.

```kotlin
// buildSrc/build.gradle.kts

plugins {
    `kotlin-dsl`
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.redmadrobot.build:infrastructure-common:0.18")
}
```

**Comment by osipxd** [comment]
A workaround is to update Gradle to 8+ which includes bundled Kotlin 1.8.10

**Comment by osipxd** [comment]
I think I found the root cause https://github.com/gradle/gradle/issues/23955
`kotlin-dsl` rewrites target Kotlin version
