### ISSUE TITLE
The Detekt plugin throws an exception in the proxy module

### ISSUE THREAD

**Issue by rwqwr** [RedMadRobot/gradle-infrastructure#81]
If the root of the gradle infrastructure is different from the root of gradle, the detekt plugin treats gradle proxy modules as subprojects and throws an exception `The "feature" modules do not contain "detekt" or the "redmadrobot.detekt" plugin.` One solution is to check that the subproject contains a build file.

**Comment by osipxd** [comment]
I think will be better to check if the module has kotlin plugin applied
